Miscellaneous build and test changes (#294)
* Disallow VLAs and other constructs on CI

vla, reorder and return-type warnings have been enabled as errors,
as these warnings often indicate problems and are easily avoidable.

-Wvla is enabled because VLAs can be used effectively for small arrays,
but a vector is more appropriate for unbounded input. This is
particularly noticeable on Windows, where the default stack size is
only 1MB. rocBLAS has built with this option for a while.

-Wreorder is enabled because out-of-order member initializer lists
have a misleading execution order, and I've only ever seen them
written that way by mistake.

-Wreturn-type is enabled because omitting a return statement from
a function that returns a value is only ever done by mistake in
modern code.

* Reduce timeout for math-ci checkin tests

The debug, precheckin and static library tests typically run in under
5 minutes, so a 45 minute timeout seems high enough to ensure it will
never be encountered unless there's a serious problem. Nevertheless,
this change should help conserve CI resources when tests stall, as the
default timeout is 5 hours.

* Use cmake --build rather than make

By using a generic cmake build call, the Ninja build system can be
used by calling './install.sh --cmake-arg -GNinja'.

* Fix build with CMake v3.21.0

The new ROCMClang compiler detection causes build failures, so disable
it until the problem has been resolved.

* Expand BDSQR tolerance

The errors seen with gfx1030 on Windows were slightly beyond the original tolerance:

../../clients/include\testing_bdsqr.hpp(593): error: Expected: ((max_errorv)) <= ((n)*get_epsilon<T>()), actual: 3.68428e-15 vs 3.33067e-15
[  FAILED  ] checkin_lapack/BDSQR.__double_complex/43, where GetParam() = ({ 15, 10, 10, 10 }, { 0, 0, 0, 0 }) (5 ms)

../../clients/include\testing_bdsqr.hpp(593): error: Expected: ((max_errorv)) <= ((n)*get_epsilon<T>()), actual: 3.41204e-15 vs 3.33067e-15
[  FAILED  ] checkin_lapack/BDSQR.__double_complex/47, where GetParam() = ({ 15, 10, 10, 10 }, { 0, 0, 0, 1 }) (4 ms)

* Promote Doxygen warnings to errors

All warnings in rocSOLVER Doxygen builds over the past few
months have indicated legitimate problems in the docs. Turning the
warnings into errors will make them more obvious.

FAIL_ON_WARNINGS would be preferable to YES, but requires a more
recent Doxygen than is provided in the ReadTheDocs container.

[ROCm/rocSOLVER commit: e4b3dc75c42dbad51ef81d9fb40bb222e7160895]