Pin 'mistune' to last known good version (#357)
This change fixes the error:

    Module 'mistune' has no attribute 'BlockGrammar'

The mistune module is used by m2r2, but the version was not specified
tightly, so the release of mistune 2.0 caused a breakage due to
interface changes.

[ROCm/rocSOLVER commit: 16df774beb7b9aa4e44f3c7215523964b59d1354]